/**
* ! This file is generated by the script, do not modify it directly
*/
import type { UDT } from "./tool";

const mainnetUDTList: UDT[] = [

  {
    name: "BANK",
    icon: "/assets/udt/default.png",
    symbol: "BANK",
    decimalPlaces: 8,
    type: {
      codeHash: "0x50bd8d6680b8b9cf98b73f3c08faf8b2a21914311954118ad6609be6e78a1b95",
      hashType: "data1",
      args: "0x3046219b8dd69e0513691568ea438ac6a2a356c0f2695f98a8aed3cc03a1061a",
    },
    typeHash: "0x73b7266e3500db7c5def31d1d8a112e86fa5c59d83f222486913836704cee3f4",
    manager: "ckb1qzpfq3n62yh9hxnts9jxnv8d4wap7jkywn3gllwkqnp203myg6a67qnhxnpq8dfryqtgasrrh6l9pv05gsl40cha43v0sqg63slf05flu5qqqqqqx8ka9y",
    tags: ["supply-limited", "rgb++"],
  },
  {
    name: "BEAF",
    icon: "/assets/udt/mainnet/beaf/beaf.jpeg",
    symbol: "BEAF",
    decimalPlaces: 0,
    type: {
      codeHash: "0x50bd8d6680b8b9cf98b73f3c08faf8b2a21914311954118ad6609be6e78a1b95",
      hashType: "data1",
      args: "0xc639759e988445217e4c08b2e7b416082d9de0cb061194e2f7f35a89bb6fbf4f",
    },
    typeHash: "0xfbd235ba8e5b1f8f7df6bd51e8756d52c05ef358d30e7bcfee8a73b6a9c185c9",
    manager: "ckb1qzpfq3n62yh9hxnts9jxnv8d4wap7jkywn3gllwkqnp203myg6a67q3w55dn90d36gqd9fxn4vfddsmmrzy7k04qpp9sfy5560ejtzl5l5qqqqqq8422du",
    tags: ["supply-limited", "rgb++"],
  },
  {
    name: "ccBTC",
    icon: "/assets/udt/mainnet/btc/btc.png",
    symbol: "BTC",
    decimalPlaces: 8,
    type: {
      codeHash: "0x092c2c4a26ea475a8e860c29cf00502103add677705e2ccd8d6fe5af3caa5ae3",
      hashType: "type",
      args: "0x68e64ba4b0daeeec45c1f983d6d574fca370442cafb805bc4265ef74870a4ac8",
    },
    typeHash: "0x3cd44aecea36e0a27e671f1fc79e65add7bf2f0e8b368389dc810ec81c63fa57",
    manager: "ckb1qzdcr9un5ezx8tkh03s46m9jymh22jruelq8svzr5krj2nx69dhjvqgx6gsml975rhjhy23mjnlg227kgskgycpsqqnr3s4r",
    tags: ["rgb++", "layer-2-asset"],
  },
  {
    name: "JOKER",
    icon: "/assets/udt/mainnet/joker/joker.png",
    symbol: "JOKER",
    decimalPlaces: 8,
    type: {
      codeHash: "0x50bd8d6680b8b9cf98b73f3c08faf8b2a21914311954118ad6609be6e78a1b95",
      hashType: "data1",
      args: "0xcb74eaded089bf39c2165149cad3d526b4321e9a6119c7ae9cf996be3acfeb18",
    },
    typeHash: "0xa9ae2d1a2459f2ad0a590358a117aaa37b44cb58307c658ff2a72654c466e148",
    manager: "ckb1qzpfq3n62yh9hxnts9jxnv8d4wap7jkywn3gllwkqnp203myg6a67qkm39rufp2nmn4nd9g8fzrukq8a83hnahedmxcye27sytxm563zdqqqqqqqvhhhya",
    tags: ["supply-limited", "rgb++"],
  },
  {
    name: "RGB++ Protocol",
    icon: "/assets/udt/mainnet/rgbpp/rgbpp.png",
    symbol: "RGB++",
    decimalPlaces: 8,
    type: {
      codeHash: "0x50bd8d6680b8b9cf98b73f3c08faf8b2a21914311954118ad6609be6e78a1b95",
      hashType: "data1",
      args: "0x08875c56644d39dd9629d291357d3026debc5d22fa88d924d60ce8f16dd50e70",
    },
    typeHash: "0xb5fdb4e8ad52f5e3ed4a294c01ca99f7811b06baef2e7fce5b7d4ebbf006717d",
    manager: "ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsq2kwmw8vqcnzg3w5wmce8z9qf5teznlaesh2hxmw",
    tags: ["rgb++", "layer-2-asset"],
  },
  {
    name: "RUSD",
    icon: "/assets/udt/mainnet/rusd/rusd.svg",
    symbol: "RUSD",
    decimalPlaces: 8,
    type: {
      codeHash: "0x26a33e0815888a4a0614a0b7d09fa951e0993ff21e55905510104a0b1312032b",
      hashType: "type",
      args: "0x360c9d87b2824c357958c23e8878f686001e88e9527a08ea229e7d9ba7fe39a7",
    },
    typeHash: "0x71ff665b40ba044b1981ea9a8965189559c8e01e8cdfa34a3cc565e1f870a95c",
    manager: "ckb1qpt0kce2zw4a44es35hqxja2u89sf85w3lere37qk62ynash2jtnxqtmqecp56kf2jx65zdgr0983xgmeglmku62zhqrxz78r0klaqrv2cssrj8t",
    tags: ["rgb++", "layer-2-asset"],
  },
  {
    name: "Seal",
    icon: "/assets/udt/mainnet/seal/seal.png",
    symbol: "Seal",
    decimalPlaces: 8,
    type: {
      codeHash: "0x50bd8d6680b8b9cf98b73f3c08faf8b2a21914311954118ad6609be6e78a1b95",
      hashType: "data1",
      args: "0x2ae639d6233f9b15545573b8e78f38ff7aa6c7bf8ef6460bf1f12d0a76c09c4e",
    },
    typeHash: "0x178fb47b597a56d48b549226aff59f750b4784250c7f40f781b64ef090a8a0a7",
    manager: "ckb1qz7xc452rgxs5z0ks3xun46dmdp58sepg0ljtae8ck0d7nah945nvqgpqqqqpg840kldpmna3xlagw8ehvggfl4ngzkd50anc936nm475wrstxf5v39jp9",
    tags: ["rgb++", "layer-1-asset", "supply-limited"],
  },
  {
    name: "USDI",
    icon: "/assets/udt/mainnet/usdi/usdi.svg",
    symbol: "USDI",
    decimalPlaces: 6,
    type: {
      codeHash: "0xbfa35a9c38a676682b65ade8f02be164d48632281477e36f8dc2f41f79e56bfc",
      hashType: "type",
      args: "0xd591ebdc69626647e056e13345fd830c8b876bb06aa07ba610479eb77153ea9f",
    },
    typeHash: "0x7f3fba3fb8d6e000176f7e1ae22e8cd02841dec6a8341dc69aeef46387a20664",
    manager: "ckb1qrgqep8saj8agswr30pls73hra28ry8jlnlc3ejzh3dl2ju7xxpjxqgqq8we8qft3s9u47pfv5c2uq4xexurymlgfc6hvrcf",
    tags: ["rgb++", "layer-2-asset"],
  },
];
export default mainnetUDTList;
