// Do not modify this file, it is auto generated by i18n-resource-plugin
import en_cell from "./en/cell.json";
import en_common from "./en/common.json";
import en_script from "./en/script.json";
import en_search from "./en/search.json";
import en_tokens from "./en/tokens.json";
import en_tools from "./en/tools.json";
import zh_cell from "./zh/cell.json";
import zh_common from "./zh/common.json";
import zh_script from "./zh/script.json";
import zh_search from "./zh/search.json";
import zh_tokens from "./zh/tokens.json";
import zh_tools from "./zh/tools.json";

const resources = {
  "en": {
    "cell": en_cell,
    "common": en_common,
    "script": en_script,
    "search": en_search,
    "tokens": en_tokens,
    "tools": en_tools,
  },
  "zh": {
    "cell": zh_cell,
    "common": zh_common,
    "script": zh_script,
    "search": zh_search,
    "tokens": zh_tokens,
    "tools": zh_tools,
  },
}

export default resources;